### ISSUE TITLE
Experiment Reproduction Help

### ISSUE THREAD

**Issue by Yepgang** [salesforce/rng-kbqa#4]
I deployed the environment as instructed. The result obtained when testing the demo script is only 0.72, which is lower than the expected 0.86.
In addition, when I did the follow-up test, the 32g ram of the computer did not seem to be enough. When I used ranker to test the dev data, the process would be killed.
Could you please give me some advice to reproduce the results?

**Comment by xiye17** [comment]
I would recommend using a machine with a larger ram. 32G seems not enough for setting up Freebase in the first place (100G is recommended in Freebase Setup repo).

For the results on the demo set, it might connect to the issue of limited memory, but I am not sure. Anyway, if you need, I can send you intermediate outputs so you can compare and figure out which step the problem lies in. Just shoot me an email at xiye@cs.utexas.edu if you need it.

**Comment by Yepgang** [comment]
thanks a lot
